### ISSUE TITLE
Fallo en las fotos 

### ISSUE THREAD

**Issue by joxex** [tristan213091028409124/proyecto_entornos#7]
Las fotos no funcionaban, por algún motivo no se veían y bueno hay que retocar eso. Miralo y me vas diciendo.

**Comment by joxex** [comment]
Se borro el código de una parte hay que retocarlo , se ve que alguien le dio sin querer y ahora hay que volver a ponerlo, me vas diciendo algo.

**Comment by josepolo00** [comment]
Vale, ya lo he revisado y lo he solucionado, el error estaba donde me habias comentado en el código
